In [1]:
print("hello world")

hello world


In [3]:
#Deep learning inspired by how the human brain learns 
#Neural networks are a set of algorithms, modeled loosely after the human brain 

In [4]:
#Pytorch Sensor # Similar to array or matrix 
#Tensors are the building blocks of deep learning

In [5]:
import torch
my_list = [[1,2,3],[4,5,6]]
my_tensor = torch.tensor(my_list)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
my_list = [[1,2,3],[4,5,6]]
my_tensor = torch.tensor(my_list)
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.device)

torch.Size([2, 3])
torch.int64
cpu


In [ ]:
import torch 
a = torch.tensor([[1,1], [2,2]])
b = torch.tensor([[2,2], [3,3]])
result = a * b 
print(result)
# row * column 

tensor([[2, 2],
        [6, 6]])


In [3]:
# First neural network in pytorch tensors 
''' Neural network consisto of input output and hidden layers 
    Input layer : dataset features 
    Ouput layer : predictions 
    Hidden layers : They lie between input and output layers and consist of various hidden layers 
'''


' Neural network consisto of input output and hidden layers \n    Input layer : dataset features \n    Ouput layer : predictions \n    Hidden layers : They lie between input and output layers and consist of various hidden layers \n'

In [4]:
# Importing as nn to avovid writing as torch.nn and 
# Input neurons : features in our dataset 
# Output : number of classes we watn to rpredit 

In [8]:
import torch
import torch.nn as nn

# Creating input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])  # Note the double square brackets

# Defining the linear layer as it applies a linear transformation to the incoming data
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)

# Passing the input through the linear layer
output = linear_layer(input_tensor)
print(output)
print(linear_layer.weight)
print(linear_layer.bias)

# Weight reflects the importance of different features 
# bias provides neuron iwth a baseline output 

tensor([[0.1981, 0.3240]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.0747, -0.0305,  0.3228],
        [-0.2709,  0.2250, -0.4945]], requires_grad=True)
Parameter containing:
tensor([0.3139, 0.1992], requires_grad=True)


In [10]:
''' Example for linear prediction using weight and bias 
Suppose we are having the 3 inputs having temrpeature humidity and wind and the output of 2 then the 
humidity will have the more significant weight to predict whether it will be cloudy or sunny 


'''

' Example for linear prediction using weight and bias \nSuppose we are having the 3 inputs having temrpeature humidity and wind and the output of 2 then the \nhumidity will have the more significant weight to predict whether it will be cloudy or sunny \n\n\n'

In [11]:
import torch.nn as nn

# Define the number of input features
n_features = 10  # Replace with the actual number of features in your data

# Define the number of output classes
n_classes = 3   # Replace with the actual number of classes in your task

# Creating the network with three linear layers
model = nn.Sequential(
    nn.Linear(n_features, 8),
    nn.Linear(8, 4),
    nn.Linear(4, n_classes)
)

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=3, bias=True)
)


In [12]:
model = nn.Sequential(nn.Linear(8,4), nn.Linear(4,2))
# First layer has 4 neurons and each neuron has 8+ 1 9 parameters and 9 *4 = 36 parameters 
total = 0 
for parameter in model.parameters():
    total  = total + parameter.numel()
print(total)

46


In [ ]:
''' Activity functions added non-linearty to the network 
    Sigmode for binary classification 
    Softmax for multi class classification 
    Suppose we are trying to know whether we have mamal or not we have 3 input layers limbs eggs hair and then 
    4 linear layers there 
     ''' 

' Activity functions added non-linearty to the network \n    Sigmode for binary classification \n    Softmax for multi class classification \n    Suppose we are trying to know whether we have mamal or not we have 3 input layers limbs eggs hair and then \n'

In [2]:
import torch 
import torch.nn as nn 

input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

'''Sigmoid is an activation function used in binary classification (e.g., yes/no predictions).

It converts logits (raw model outputs) into probabilities.

Output range: (0, 1) (useful for probabilities).

Example use case: Final layer in a binary classifier (e.g., spam detection).'''

tensor([[0.9975]])


'Sigmoid is an activation function used in binary classification (e.g., yes/no predictions).\n\nIt converts logits (raw model outputs) into probabilities.\n\nOutput range: (0, 1) (useful for probabilities).\n\nExample use case: Final layer in a binary classifier (e.g., spam detection).'

In [4]:
'''
 1.0 |        *
     |       *
     |      *
     |     *
0.5 |----*---------
     |   *
     |  *
     | *
0.0 +----------------
      -6  0  6            '''

'\n 1.0 |        *\n     |       *\n     |      *\n     |     *\n0.5 |----*---------\n     |   *\n     |  *\n     | *\n0.0 +----------------\n      -6  0  6            '

In [5]:
import torch 
import torch.nn as nn 

# 1. Create a 1x3 tensor (3 raw scores/logits for 3 classes)
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])

# 2. Initialize Softmax (dim=-1 applies it to the last dimension)
probabilities = nn.Softmax(dim=-1)

# 3. Apply Softmax to convert logits to probabilities
output_tensor = probabilities(input_tensor)

# 4. Print the result
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [6]:
'''
Concept	Key Takeaway
Softmax	Converts logits to probabilities for multi-class problems. Sums to 1.
Sigmoid	Used for binary classification. Outputs independent probabilities (0 to 1).
Use Case	Use Softmax for >2 classes, Sigmoid for 2 classes.
PyTorch	nn.Softmax(dim=1) for probabilities, CrossEntropyLoss for training
 '''

'\nConcept\tKey Takeaway\nSoftmax\tConverts logits to probabilities for multi-class problems. Sums to 1.\nSigmoid\tUsed for binary classification. Outputs independent probabilities (0 to 1).\nUse Case\tUse Softmax for >2 classes, Sigmoid for 2 classes.\nPyTorch\tnn.Softmax(dim=1) for probabilities, CrossEntropyLoss for training\n '

In [ ]:
# Forward passs : input data flows through layers calculations performed at each other 
# Output is based on weights and biases 
# Used for traning and prediction 
# Possible classifications : binary classifications , multi-class classification 

import torch 
import torch.nn as nn 
input_tensor = torch.tensor([[0.1234, 0.5678, 0.9012, 0.3456, 0.7890, 0.2345],
        [0.9876, 0.4321, 0.1098, 0.6789, 0.3210, 0.8765],
        [0.5432, 0.8765, 0.2109, 0.9012, 0.4567, 0.1234],
        [0.7654, 0.2198, 0.5432, 0.1098, 0.8901, 0.3456],
        [0.3210, 0.6543, 0.9876, 0.2345, 0.5678, 0.8901]])

# Suppose we have 5 * 6 shape where there are 5 animals and six features 
# Creating the model using sigmoid function which is used for binary classification 

model = nn.Sequential(
nn.Linear(6 ,4),
nn.Linear(4,1),
nn.Sigmoid() # sigmoid activation function 

)

output = model(input_tensor)
print(output)

''' 
Here, input dimension = 6 (6 features of each animal), output dimension = 4 (4 neurons).
This reduces/expands the feature information — from 6 features into 4 new learned features
nn.Linear(4, 1)
Now the output of first layer (size 4) is passed into another linear layer.
Input = 4, Output = 1.

'''

tensor([[0.5701],
        [0.5795],
        [0.5344],
        [0.5959],
        [0.5879]], grad_fn=<SigmoidBackward0>)


' \nHere, input dimension = 6 (6 features of each animal), output dimension = 4 (4 neurons).\nThis reduces/expands the feature information — from 6 features into 4 new learned features\nnn.Linear(4, 1)\nNow the output of first layer (size 4) is passed into another linear layer.\nInput = 4, Output = 1.\n'

In [ ]:
'''
Why Linear layers?

They learn the relationships between features and outputs.
No non-linearity until activation function is added.

Why Sigmoid?
For binary classification to predict a probability between 0 and 1.
Otherwise (for multiclass classification), you'd use something else like Softmax. '''


"\nWhy Linear layers?:\n\nThey learn the relationships between features and outputs.\n\nNo non-linearity until activation function is added.\n\nWhy Sigmoid?:\n\nFor binary classification to predict a probability between 0 and 1.\n\nOtherwise (for multiclass classification), you'd use something else like Softmax. "

In [5]:
import torch
import torch.nn as nn

''' 
class 1 - mammal 
class 2 - bird 
class 3 - reptile 
'''

n_classes = 3

# Creating the multiclass classification model
model = nn.Sequential(
    nn.Linear(6, 4),    # First Linear layer: input 6 features -> output 4 features
    nn.Linear(4, n_classes),  # Second Linear layer: 4 features -> 3 class scores
    nn.Softmax(dim=-1)  # Softmax activation across the classes
)


'''1. nn.Linear(6, 4)
Input: 6 features (example: weight, size, temperature, etc.)

Output: 4 neurons (abstract features learned by the network).

Purpose:

Transform the raw input into new feature representations.

2. nn.Linear(4, n_classes)
(where n_classes = 3)

Input: 4 features (from the previous layer).

Output: 3 numbers (one for each class: mammal, bird, reptile).

Purpose:

Produce raw scores (called logits) for each class.'''


output = model(input_tensor)
print(output.shape)
print(output)



torch.Size([5, 3])
tensor([[0.1915, 0.3374, 0.4711],
        [0.1678, 0.2989, 0.5333],
        [0.1790, 0.3133, 0.5077],
        [0.1812, 0.3154, 0.5034],
        [0.1718, 0.3356, 0.4927]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# Regression model regression → the output should be a continuous real number, not probabilities.
import torch
import torch.nn as nn

# 11 input features
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 64),   # Layer 1: 11 → 64
    nn.Linear(64, 32),   # Layer 2: 64 → 32
    nn.Linear(32, 16),   # Layer 3: 32 → 16
    nn.Linear(16, 1)     # Layer 4: 16 → 1 (regression output)
)

output = model(input_tensor)
print(output)


tensor([[0.6023]], grad_fn=<AddmmBackward0>)


In [1]:
import torch
import torch.nn as nn

# Sample input: 11 features
input_tensor = torch.tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]], dtype=torch.float)

# Define a simple feedforward neural network with 4 layers
class RegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(11, 64)
        self.layer2 = nn.Linear(64, 32)
        self.layer3 = nn.Linear(32, 16)
        self.output = nn.Linear(16, 1)  # Final layer for regression

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.output(x)
        return x

# Create the model and run it on the input
model = RegressionModel()
output = model(input_tensor)

print("Regression Output:", output.item())


Regression Output: -0.33058786392211914


In [ ]:
''' A regression model in machine learning predicts real-valued outputs (e.g., house price, temperature, or stock price). Unlike classification (which predicts discrete categories), regression answers questions like:

"What is the price?"

"What is the expected value?"

"How much will it be?"

Architecture:

nn.Linear(11, 64) – first hidden layer.

nn.Linear(64, 32) – second hidden layer.

nn.Linear(32, 16) – third hidden layer.

nn.Linear(16, 1) – output layer predicting a single continuous value.

This kind of model can be used for tasks like:

Predicting house prices based on 11 features (size, location, etc.)

Estimating car mileage
    
Forecasting sales or demand


'''

' A regression model in machine learning predicts real-valued outputs (e.g., house price, temperature, or stock price). Unlike classification (which predicts discrete categories), regression answers questions like:\n\n"What is the price?"\n\n"What is the expected value?"\n\n"How much will it be?"\n\nArchitecture:\n\nnn.Linear(11, 64) – first hidden layer.\n\nnn.Linear(64, 32) – second hidden layer.\n\nnn.Linear(32, 16) – third hidden layer.\n\nnn.Linear(16, 1) – output layer predicting a single continuous value.\n\nThis kind of model can be used for tasks like:\n\nPredicting house prices based on 11 features (size, location, etc.)\n\nEstimating car mileage\n\nForecasting sales or demand\n\n\n'

In [3]:
# Loss function tells us how good out model is during traning 
# Takes a model prediction y and ground truth y 
# Outputs a float 
 # Class 0 - mamal , class 1 - bird , class 2 - reptile 

# Predicted class = 0 - > correct = low loss 
# Predicted class = 1 -> wrong = high loss 
# Predicted class = 2 - > wrong = high loss 

# Our goal is to minimise the loss 

''' 
loss = F(y , y^)
y is a single integer ( class label )
eg : y = 0 when y is a mammal and y^ is a tensor (prediction before the softmax )

'''

' \nloss = F(y , y^)\ny is a single integer ( class label )\neg : y = 0 when y is a mammal and y^ is a tensor (prediction before the softmax )\n\n'

In [7]:
import torch 
import torch.nn.functional as F
print(F.one_hot(torch.tensor(0), num_classes= 3 ))
print(F.one_hot(torch.tensor(1), num_classes= 3 ))

'''  
F.one_hot() converts class indices to one-hot vectors.

CrossEntropyLoss expects raw logits and integer class labels, not one-hot.

One-hot targets are common in some contexts (like manual loss calculation), but not for CrossEntropyLoss.'''

tensor([1, 0, 0])
tensor([0, 1, 0])


'  \nF.one_hot() converts class indices to one-hot vectors.\n\nCrossEntropyLoss expects raw logits and integer class labels, not one-hot.\n\nOne-hot targets are common in some contexts (like manual loss calculation), but not for CrossEntropyLoss.'

In [9]:
from torch.nn import CrossEntropyLoss
scores = torch.tensor([-5.2, 4.6 , 0.8])
one_hot_target = torch.tensor([1,0,0])
criterion = CrossEntropyLoss()
print(criterion(scores.double(), one_hot_target.double()))
# scores - > model prediction before the final softmax function 

tensor(9.8222, dtype=torch.float64)


In [10]:
import torch
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss

y = [2]  # True class index
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Make sure the number of classes matches the scores
num_classes = scores.size(1)

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes=num_classes)

print("One-hot label:", one_hot_label)


One-hot label: tensor([[0, 0, 1, 0]])


In [ ]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F
from torch.nn  import CrossEntropyLoss

# Dummy input sample (e.g., batch size of 1, 16 features)
sample = torch.randn(1, 16)

# Target class index (e.g., class 1 out of 2 classes)
target = torch.tensor([1])  # Not one-hot

# Define the model
model = nn.Sequential(
    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Linear(8, 4),
    nn.ReLU(),
    nn.Linear(4, 2)
)

# Forward pass
prediction = model(sample)

# Compute loss
criterion = CrossEntropyLoss()
loss = criterion(prediction, target)

# Backward pass (compute gradients)
loss.backward()

# Output results
print("Predicted scores:", prediction)
print("Loss:", loss.item())


lr = 0.001 
#update weight
weight = model[0].weight.grad 

weight = weight - lr * weight_grad 


bias = model[0].bias 
bias_grad = model[0].bias.grad 
bias = bias - lr * bias_grad


Predicted scores: tensor([[0.3353, 0.2086]], grad_fn=<AddmmBackward0>)
Loss: 0.7585461139678955


In [12]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(16, 8),
    nn.Linear(8, 2)
)

# Access the weight of the first linear layer
weight_0 = model[0].weight
print("Weight of the first layer:", weight_0)

# Access the bias of the second linear layer
bias_1 = model[1].bias
print("Bias of the second layer:", bias_1)


Weight of the first layer: Parameter containing:
tensor([[-0.0016,  0.0710, -0.1597,  0.1314, -0.0631,  0.1496,  0.0433, -0.1203,
          0.2097, -0.2100, -0.2428,  0.2067, -0.0999, -0.0224,  0.1810, -0.0837],
        [ 0.0522,  0.0321, -0.0552,  0.0896,  0.0600, -0.0477,  0.1040, -0.1005,
          0.1819,  0.0745, -0.0448,  0.0475,  0.0555,  0.0107,  0.1110,  0.0352],
        [-0.1728,  0.2453, -0.1308,  0.0069,  0.1282, -0.0652, -0.1577,  0.1036,
          0.0088, -0.1682,  0.1106, -0.2384,  0.2132, -0.0564, -0.0476,  0.0953],
        [ 0.1532, -0.1204, -0.1741, -0.1092,  0.1336,  0.0855, -0.0914,  0.0178,
         -0.0387,  0.1673, -0.0342,  0.0159, -0.1545, -0.1112, -0.1789,  0.1022],
        [ 0.0872,  0.0486,  0.0877,  0.0915, -0.1102,  0.0166, -0.0491,  0.0310,
         -0.0378, -0.0093,  0.0734,  0.0013, -0.1971,  0.1535,  0.1534,  0.0510],
        [ 0.0990,  0.0209, -0.2135, -0.0952, -0.0942, -0.2168,  0.1342, -0.2235,
          0.2083, -0.1552, -0.0822,  0.1147, -0.0501,  

In [13]:
# # Assuming input_data is your input tensor (e.g., features from your dataset)
# pred = model(input_data)

# # Compute the loss
# loss = criterion(pred, target)

# # Perform backward pass to compute gradients
# loss.backward()

# # Update model's parameters using the optimizer
# optimizer.step()

# # Optionally, zero the gradients
# optimizer.zero_grad()


In [2]:
import torch
import torch.nn as nn

# Create a model with ReLU activation function between layers
model = nn.Sequential(
    nn.Linear(16, 8),
    nn.ReLU(),  # Adding ReLU activation function
    nn.Linear(8, 2)
)

# Access the weight of the first linear layer
weight_0 = model[0].weight
print("Weight of the first layer:", weight_0)

# Access the bias of the second linear layer
bias_1 = model[2].bias  # We are accessing the second linear layer after ReLU
print("Bias of the second layer:", bias_1)


Weight of the first layer: Parameter containing:
tensor([[-0.0545,  0.2350,  0.1334, -0.2137, -0.1480,  0.0091, -0.0921,  0.1934,
         -0.0367, -0.0410, -0.2262,  0.1300,  0.0238,  0.0848, -0.0232, -0.2380],
        [-0.0800,  0.0611,  0.2315,  0.2148, -0.1206,  0.1076, -0.1219, -0.1809,
         -0.0708, -0.0717,  0.0088, -0.0642, -0.1042, -0.1648, -0.0629, -0.0540],
        [ 0.1518, -0.1828, -0.2389,  0.0515,  0.0201, -0.2300, -0.2214, -0.2029,
          0.1064, -0.1619, -0.1913,  0.0437,  0.0385, -0.0733,  0.1596,  0.0068],
        [-0.0049,  0.1370,  0.0761, -0.0721,  0.1083,  0.1089, -0.1589, -0.0835,
          0.0488,  0.0819, -0.0580,  0.0243,  0.1734, -0.1749,  0.2279, -0.0200],
        [ 0.0183,  0.1573,  0.1035,  0.0418, -0.1157,  0.0686, -0.2041, -0.2423,
          0.0886, -0.2293, -0.1751, -0.0344,  0.1027,  0.0513,  0.1926, -0.1265],
        [ 0.1844, -0.1980, -0.1908, -0.0189, -0.1149,  0.2409,  0.0301, -0.0925,
          0.0381, -0.0279, -0.2285,  0.0685, -0.0602,  

In [1]:
# Regression model in relu function
''' Keras Regression Model with ReLU'''
import torch
import torch.nn as nn

# Define the model
class SimpleRegressionModel(nn.Module):
    def __init__(self, input_size):
        super(SimpleRegressionModel, self).__init__()
        self.fc = nn.Linear(input_size, 1)  # Single output unit (for regression)

    def forward(self, x):
        return self.fc(x)

# Example input and target
inputs = torch.randn(5, 10)  # 5 samples, 10 features each
targets = torch.randn(5, 1)  # 5 target values

# Create the model
model = SimpleRegressionModel(input_size=10)

# Define loss function and optimizer
criterion = nn.MSELoss()  # Mean Squared Error for regression
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Training loop (one iteration for simplicity)
optimizer.zero_grad()     # Zero the gradients
outputs = model(inputs)   # Forward pass
loss = criterion(outputs, targets)  # Calculate loss
loss.backward()           # Backward pass
optimizer.step()          # Update the weights

print(f'Loss: {loss.item():.4f}')



Loss: 2.5076


In [1]:
import torch
import torch.nn as nn
import torchmetrics
import numpy as np

# --- Layer Initialization ---
layer0 = nn.Linear(16, 32)
layer1 = nn.Linear(32, 64)

# Initialize weights with uniform distribution
nn.init.uniform_(layer0.weight)
nn.init.uniform_(layer1.weight)

model_layers = nn.Sequential(layer0, layer1)

# --- Evaluation Loop ---
def evaluate(model, validationloader, criterion):
    model.eval()  # Set model to evaluation mode
    validation_loss = 0.0

    with torch.no_grad():
        for features, labels in validationloader:
            outputs = model(features)
            loss = criterion(outputs, labels)
            validation_loss += loss.item()

    validation_loss_epoch = validation_loss / len(validationloader)
    print(f"Validation loss: {validation_loss_epoch:.4f}")

    model.train()  # Set back to training mode
    return validation_loss_epoch

# --- Accuracy calculation using torchmetrics ---
def accuracy_epoch(model, dataloader):
    metric = torchmetrics.Accuracy(task="multiclass", num_classes=3)
    for features, labels in dataloader:
        outputs = model(features)
        metric.update(outputs, labels.argmax(dim=-1))

    accuracy = metric.compute()
    print(f"Accuracy on all data: {accuracy:.4f}")
    metric.reset()
    return accuracy

# --- Dropout example ---
def dropout_example(features):
    model = nn.Sequential(
        nn.Linear(8, 6),
        nn.Linear(6, 4),
        nn.Dropout(p=0.5)
    )
    # Train mode (Dropout active)
    model.train()
    output_train = model(features)

    # Eval mode (Dropout disabled)
    model.eval()
    output_eval = model(features)

    print("Output in train mode:", output_train)
    print("Output in eval mode:", output_eval)

# --- Random Search for Hyperparameters ---
def random_search():
    values = []
    for idx in range(10):
        # Randomly sample a learning rate factor between 2 and 4
        factor = np.random.uniform(2, 4)
        lr = 10 ** -factor
        
        # Randomly select momentum between 0.85 and 0.99
        momentum = np.random.uniform(0.85, 0.99)
        
        values.append((lr, momentum))
    # Assuming plot_hyperparameter_search(values) is defined elsewhere
    # plot_hyperparameter_search(values)
    return values

# --- Example usage (assuming DataLoader, criterion, etc. are defined) ---
# features, labels, validationloader, dataloader, and criterion should be defined in your actual usage context

if __name__ == "__main__":
    # Example tensor for dropout example (batch_size=5, features=8)
    example_features = torch.randn(5, 8)
    dropout_example(example_features)

    # Run random search and print results
    hyperparams = random_search()
    print("Random search results (lr, momentum):")
    for lr, mom in hyperparams:
        print(f"LR: {lr:.6f}, Momentum: {mom:.4f}")

    # Evaluation and accuracy require actual data loaders and criterion
    # Uncomment and provide those to run:
    # val_loss = evaluate(model_layers, validationloader, criterion)
    # acc = accuracy_epoch(model_layers, dataloader)


ModuleNotFoundError: No module named 'torchmetrics'